#pragma once

#include "CommonDefinitions.h"

#pragma pack(1)

enum D2Composits
{
	COMPOSIT_HEAD,
	COMPOSIT_TORSO,
	COMPOSIT_LEGS,
	COMPOSIT_RIGHTARM,
	COMPOSIT_LEFTARM,
	COMPOSIT_RIGHTHAND,
	COMPOSIT_LEFTHAND,
	COMPOSIT_SHIELD,
	COMPOSIT_SPECIAL1,
	COMPOSIT_SPECIAL2,
	COMPOSIT_SPECIAL3,
	COMPOSIT_SPECIAL4,
	COMPOSIT_SPECIAL5,
	COMPOSIT_SPECIAL6,
	COMPOSIT_SPECIAL7,
	COMPOSIT_SPECIAL8,
	NUM_COMPONENTS,
};

enum D2WeaponClasses
{
	WEAPONCLASS_NONE,
	WEAPONCLASS_BOW,
	WEAPONCLASS_1HS,
	WEAPONCLASS_1HT,
	WEAPONCLASS_STF,
	WEAPONCLASS_2HS,
	WEAPONCLASS_2HT,
	WEAPONCLASS_XBW,
	WEAPONCLASS_1JS,
	WEAPONCLASS_1JT,
	WEAPONCLASS_1SS,
	WEAPONCLASS_1ST,
	WEAPONCLASS_HT1,
	WEAPONCLASS_HT2,
	NUM_WEAPON_CLASSES,

};

struct D2CompositStrc
{
	int32_t nWeaponClassCode;					//0x00
	int32_t nWeaponClassId;						//0x04
};

#pragma pack()
